services:
  db:
    container_name: bakery
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 3308:5432
    environment:
      POSTGRES_USER: jvg_25
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: localhost
      POSTGRES_DB: bakery_db
    restart: always

volumes:
  postgres-data: