services:
  bakery_backend:
    container_name: bakery_backend
    build: .
    ports:
      - "5000:5000"
    depends_on:
      bakery_db:
        condition: service_healthy
    env_file:
      - ./.env
  bakery_db:
    container_name: ${BAKERY_DB_NAME}
    image: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${BAKERY_DB_USERNAME}
      - POSTGRES_PASSWORD=${BAKERY_DB_PASSWORD}
      - POSTGRES_DB=${BAKERY_DB_NAME}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

volumes:
  postgres-data:
    name: postgres-data